import React from 'react'
import Script from 'next/script';
function page() {
    return (
        <div>
            <Script>
                {`alert("welcome to about")`}
            </Script>
            about
        </div>
    )
}

export default page




export const metadata = {
    title: "about fb",
    description: "Generated by create next app",
};

